// =============================================================================
// .NET ASPIRE APP HOST - Orchestration Entry Point
// =============================================================================
// The AppHost is the central orchestrator for your distributed application.
// It declares all services, resources, and their dependencies in code.
// When you run this project, Aspire:
//   1. Discovers all declared services and resources
//   2. Starts them in the correct order based on dependencies (WaitFor)
//   3. Injects configuration (connection strings, endpoints) automatically
//   4. Provides a dashboard for monitoring, logs, and traces
//
// Learn more: https://learn.microsoft.com/dotnet/aspire/fundamentals/app-host-overview
// =============================================================================

// Create the distributed application builder - this is the entry point for
// defining your application's architecture. Similar to WebApplication.CreateBuilder()
// but for orchestrating multiple services.
var builder = DistributedApplication.CreateBuilder(args);

// =============================================================================
// CONNECTION STRINGS
// =============================================================================
// AddConnectionString() references an existing connection string from configuration
// (appsettings.json, user secrets, or environment variables).
// Unlike AddSqlServer() which provisions a new container, this uses an external
// database - in this case, the SQL Server from the devcontainer.
// The connection string is read from: ConnectionStrings:MedicalDb
var medicalDbConnectionString = builder.AddConnectionString("MedicalDb");

// =============================================================================
// MCP SERVER PROJECT
// =============================================================================
// AddProject<T>() registers a .NET project as a service in the Aspire orchestration.
// The generic parameter (Projects.MedicalDbMcpServer) is auto-generated by Aspire
// from the project reference - it provides compile-time safety.
//
// The string "mcp-server" is the resource name used for:
//   - Service discovery (other services can reach it via http://mcp-server)
//   - Dashboard display
//   - Logging and tracing correlation
var mcpServer = builder.AddProject<Projects.MedicalDbMcpServer>("mcp-server")
    // WithReference() injects the connection string into this service's configuration.
    // The MCP server will receive the connection string as ConnectionStrings:MedicalDb
    // in its IConfiguration, enabling it to connect to the database.
    .WithReference(medicalDbConnectionString);

// Azure OpenAI connection string for AI capabilities
// Retrieved from configuration: ConnectionStrings:openai
// This follows the format: Endpoint=https://xxx.openai.azure.com;Key=xxx
var openai = builder.AddConnectionString("openai");

// =============================================================================
// AGENT API PROJECT
// =============================================================================
// The main API that orchestrates AI queries using the MCP server's tools.
builder.AddProject<Projects.MedicalAgent_Api>("agent-api")
    // WithReference(mcpServer) enables SERVICE DISCOVERY:
    // The Agent API can reach the MCP server using the URL "http://mcp-server"
    // Aspire automatically resolves this to the actual endpoint at runtime.
    // This eliminates hard-coded URLs and works across local dev and deployment.
    .WithReference(mcpServer)
    // WithReference(openai) injects the Azure OpenAI connection string
    // into the Agent API's configuration as ConnectionStrings:openai
    .WithReference(openai)
    // WaitFor() ensures the Agent API doesn't start until the MCP server
    // is healthy and ready. This prevents startup race conditions where
    // the API might try to connect before the MCP server is available.
    // Dependencies are resolved in order: MedicalDb -> MCP Server -> Agent API
    .WaitFor(mcpServer);

// =============================================================================
// BUILD AND RUN
// =============================================================================
// Build() materializes all the configuration into a runnable application.
// Run() starts the Aspire dashboard and all orchestrated services.
// The dashboard (typically at https://localhost:15xxx) provides:
//   - Real-time logs from all services
//   - Distributed tracing across service calls
//   - Resource status and health checks
//   - Environment variables and configuration inspection
builder.Build().Run();
